---
title: "Overview of built-in codebooks"
output: html_document
---

Before creating your own codebooks, you might want to explore the built-in codebooks available in the `quallmer` package. These codebooks are designed to streamline common annotation needs and can be easily integrated into your workflow.

## Built-in codebooks

The `quallmer` package currently includes the following built-in codebooks:

| **Task** | **Function** | **Description** | **Output** |
|-----------|---------------|-----------------|-------------|
| [**Sentiment analysis**](https://seraphinem.github.io/quallmer/articles/pkgdown/examples/codebook_sentiment.html) | `codebook_sentiment()` | Rates overall sentiment of text. | Sentiment score (`-1` to `1`) and explanation |
| [**Stance detection**](https://seraphinem.github.io/quallmer/articles/pkgdown/examples/codebook_stance.html) | `codebook_stance()` | Identifies stance/position taking toward a topic. | Stance label (pro/neutral/contra) and explanation |
| [**Ideological scaling**](https://seraphinem.github.io/quallmer/articles/pkgdown/examples/codebook_ideology.html) | `codebook_ideology()` | Places text on an ideological scale (0–10) for a specified dimension. | Ideological score (`0` to `10`) and explanation |
| [**Topic salience**](https://seraphinem.github.io/quallmer/articles/pkgdown/examples/codebook_salience.html) | `codebook_salience()` | Ranks salience of specified topics in text. | Ranked list of topics and explanation |
| [**Fact-checking**](https://seraphinem.github.io/quallmer/articles/pkgdown/examples/codebook_fact.html) | `codebook_fact()` | Verifies factual claims in text. | Truthfulness score (0-10, with 10 signalling highest confidence in truthfulness), misleading topics (if any) and explanation |



If you wish to create custom codebooks tailored to your specific research questions and data types, you can use the `qlm_codebook()` function. This function allows you to specify the instructions and output structure, enabling you to customize the annotation process according to your needs. For a tutorial on how to create custom codebooks, please refer to our [custom codebooks tutorial](https://seraphinem.github.io/quallmer/articles/pkgdown/tutorials/custom-codebook.html).
